/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppReadinessRouteImport } from './routes/app.readiness'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as AppEventsEventIdSimulateRouteImport } from './routes/app.events.$eventId.simulate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)
const AppEventsEventIdSimulateRoute =
  AppEventsEventIdSimulateRouteImport.update({
    id: '/simulate',
    path: '/simulate',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/map': typeof AppMapRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/': typeof AppEventsIndexRoute
  '/app/events/$eventId/simulate': typeof AppEventsEventIdSimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/map': typeof AppMapRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events': typeof AppEventsIndexRoute
  '/app/events/$eventId/simulate': typeof AppEventsEventIdSimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/map': typeof AppMapRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/': typeof AppEventsIndexRoute
  '/app/events/$eventId/simulate': typeof AppEventsEventIdSimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/events'
    | '/app/map'
    | '/app/readiness'
    | '/app/reports'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/'
    | '/app/events/$eventId/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/map'
    | '/app/readiness'
    | '/app/reports'
    | '/app'
    | '/app/events/$eventId'
    | '/app/events'
    | '/app/events/$eventId/simulate'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/events'
    | '/app/map'
    | '/app/readiness'
    | '/app/reports'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/'
    | '/app/events/$eventId/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/app/events/$eventId/simulate': {
      id: '/app/events/$eventId/simulate'
      path: '/simulate'
      fullPath: '/app/events/$eventId/simulate'
      preLoaderRoute: typeof AppEventsEventIdSimulateRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdSimulateRoute: typeof AppEventsEventIdSimulateRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdSimulateRoute: AppEventsEventIdSimulateRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppMapRoute: typeof AppMapRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEventsRoute: AppEventsRouteWithChildren,
  AppMapRoute: AppMapRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
